### ISSUE TITLE
Error | while trying anchor_generation_demo, run_training and run_validation

### ISSUE THREAD

**Issue by rrklearn2020** [asharakeh/bayes-od-rc#4]
Hi @asharakeh , Congratulations on the great work and thanks for releasing your code! 

I was trying the code, but encountered three errors.

**System details**
`python  3.6.9 
CUDA 10.1
Ubuntu 18.04
tensorflow-estimator==2.3.0
tensorflow-gpu==2.3.1
tensorflow-probability==0.11.1`

Note: data sets (folder structure for both BDD and KITTI) are configured as per the instructions.

**Situation 1:** While trying to run `python ./bayes-od-rc/demos/retina_net/anchor_generation_demo.py`

`2020-11-14 17:55:37.335822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10777 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-11-14 17:55:38.637570: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: KeyError: 'category'
Traceback (most recent call last):

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 212, in _read_labels
    frame_labels = [label for label in self.labels if

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 214, in <listcomp>
    'category'] in categories]

KeyError: 'category'

Traceback (most recent call last):
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
2020-11-14 17:55:38.657609: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: KeyError: 'category'
Traceback (most recent call last):

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 212, in _read_labels
    frame_labels = [label for label in self.labels if

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 214, in <listcomp>
    'category'] in categories]

KeyError: 'category'

tensorflow.python.framework.errors_impl.UnknownError: KeyError: 'category'
Traceback (most recent call last):

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 212, in _read_labels
    frame_labels = [label for label in self.labels if

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 214, in <listcomp>
    'category'] in categories]

KeyError: 'category'

	 [[{{node input_data/EagerPyFunc}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bayes-od-rc/demos/retina_net/anchor_generation_demo.py", line 155, in <module>
    main()
  File "./bayes-od-rc/demos/retina_net/anchor_generation_demo.py", line 93, in main
    for sample_dict in dataset.take(1):
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.UnknownError: KeyError: 'category'
Traceback (most recent call last):

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 212, in _read_labels
    frame_labels = [label for label in self.labels if

  File "….../BNN_ws/bayes-od-rc/src/retina_net/datasets/bdd/bdd_dataset_handler.py", line 214, in <listcomp>
    'category'] in categories]

KeyError: 'category'

	 [[{{node input_data/EagerPyFunc}}]]`

**Situation 2:** While trying to train using `python ./bayes-od-rc/src/retina_net/experiments/run_training.py --yaml_path='./bayes-od-rc/src/retina_net/configs/retinanet_bdd_covar.yaml'`
(same error while using run_inference.py)

_Error details are shared below_
`  File "….../BNN_ws/bayes-od-rc/src/retina_net/models/multitask_headers.py", line 31, in __init__
    kernel_regularizer=keras.regularizers.l2(l2_norm_rate))
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/keras/regularizers.py", line 306, in __init__
    _check_penalty_number(l2)
  File "….../.virtualenvs/bayes-od-rc/lib/python3.6/site-packages/tensorflow/python/keras/regularizers.py", line 37, in _check_penalty_number
    'expected an int or float value').format(x))
ValueError: Value: 1e-6 is not a valid regularization penalty number, expected an int or float value`

For this error, I changed "`l2_norm_rate: 0.0000001`" in yaml files and it worked. but the error in the situation 1 occurs `KeyError: 'category'.` Details shared above in situation.

**Situation 3:** While trying to train using `python ./bayes-od-rc/src/retina_net/experiments/run_training.py --yaml_path='./bayes-od-rc/src/retina_net/configs/retinanet_bdd_covar.yaml'` with KITTI data set.

`2020-11-14 18:56:30.315633: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.80.2
2020-11-14 18:56:30.315667: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 450.80.2
2020-11-14 18:56:30.315685: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 450.80.2
test
[]
Traceback (most recent call last):
  File "./bayes-od-rc/src/retina_net/experiments/run_training.py", line 300, in <module>
    main()
  File "./bayes-od-rc/src/retina_net/experiments/run_training.py", line 296, in main
    train_model(config)
  File "./bayes-od-rc/src/retina_net/experiments/run_training.py", line 29, in train_model
    dataset_config, 'train')
  File "/home/rr/BNN_ws/bayes-od-rc/src/retina_net/builders/dataset_handler_builder.py", line 16, in build_dataset
    dataset_handler = KittiDatasetHandler(dataset_config, train_val_test)
  File "/home/rr/BNN_ws/bayes-od-rc/src/retina_net/datasets/kitti/kitti_dataset_handler.py", line 58, in __init__
    self.data_split, possible_splits))
ValueError: Invalid dataset_split: train. Possible splits include: []`

It would be helpful, if you could guide me to try the code.

**Comment by asharakeh** [comment]
Please check pytorch code for BayesOD [here](https://github.com/asharakeh/pod_compare). This repo has been retired.
